### ISSUE TITLE
微信打开https地址页面调试抓取不到

### ISSUE THREAD

**Issue by jonnywang** [zobor/bproxy#16]
地址已经抓取到，也注入了inspect.js ，但点击“页面调试”按钮后老样子，没有发现可调试的网址

**Comment by zobor** [comment]
可以看下是不是这样的场景，《[MacOS Safari 不能使用调试工具](http://blog.bproxy.cn/post/2022/bproxy-qa/)》。
IOS系统的话，也是类似。

**Comment by jonnywang** [comment]
不行， 尝试在macos微信客户端也一样
htttps日志能抓到，但页面调试按钮无效

**Comment by jonnywang** [comment]
日志点击单个链接后栏目自动左右拆分，此时再点击另外的请求后就自动收回了拆分，能不能继续右侧栏保持显示新的请求信息

**Comment by zobor** [comment]
> 不行， 尝试在macos微信客户端也一样 htttps日志能抓到，但页面调试按钮无效

IOS 微信是不支持页面调试的。

**Comment by zobor** [comment]
> 日志点击单个链接后栏目自动左右拆分，此时再点击另外的请求后就自动收回了拆分，能不能继续右侧栏保持显示新的请求信息

这个提议，ok的。

**Comment by jonnywang** [comment]
> 
http链接测试可以哦

**Comment by jonnywang** [comment]
> > 不行， 尝试在macos微信客户端也一样 htttps日志能抓到，但页面调试按钮无效
> 
> IOS 微信是不支持页面调试的。


http链接测试可以哦

**Comment by zobor** [comment]
> 

是的，bproxy针对http处理过了，IOS的Safari内核，默认开启了NSURLSession WebSocket，导致wss不走bproxy代理了。
安卓下的微信，https也是ok的。
