### ISSUE TITLE
执行bproxy 报 '../server-build/proxy/bash' 不存在的错误

### ISSUE THREAD

**Issue by jafshare** [zobor/bproxy#20]
通过 npm 全局安装后，执行 bproxy 报以下的错误，发现是导入的路径不存在

![image](https://github.com/zobor/bproxy/assets/39552989/7d3721db-5073-4b94-bcbb-9f318bfd22cf)

**Comment by zobor** [comment]
> 通过 npm 全局安装后，执行 bproxy 报以下的错误，发现是导入的路径不存在
> 
> ![image](https://private-user-images.githubusercontent.com/39552989/289332106-7d3721db-5073-4b94-bcbb-9f318bfd22cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNTk3NjcsIm5iZiI6MTcwMjI1OTQ2NywicGF0aCI6Ii8zOTU1Mjk4OS8yODkzMzIxMDYtN2QzNzIxZGItNTA3My00Yjk0LWJjYmItOWYzMThiZmQyMmNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDAxNTEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhMjEzYjRmMWRlYWQxYmZhYTNhMjQyMzZiZDQ1ODg2Yjg5Y2YwOTgyMWJiZTNlMjlhYjc0MjQyZmQxZDAzYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hTO44r1Cdurc9Nj6F0BOKBECUSgPE0TiEYksw8S4Bu8)

项目少提交了一个npm配置文件，已修复：https://github.com/zobor/bproxy/commit/505b6f55e1f1447bfe536136149940f138f4ac4e

**Comment by jafshare** [comment]
感谢，最新版已经可以了

**Comment by zobor** [comment]
> 感谢，最新版已经可以了

感谢使用&反馈 ~
